name: brainfuck
version: '0.0.0.1'
category: TODO
author: Brooklyn Zelenka
maintainer: be.zelenka@gmail.com
copyright: © 2017 Brooklyn Zelenka
license: MIT
license-file: LICENSE.md
github: expede/brainfuck
tested-with: GHC==8.0.1 GHC==8.0.2 GHC==8.2.1
extra-source-files:
  - README.md
  - CHANGELOG.md

ghc-options:
  - -Wall
  # as recommended in:
  # https://functor.tokyo/blog/2017-07-28-ghc-warnings-you-should-enable
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates

dependencies:
  - base
  - bytestring
  - classy-prelude
  - lens
  - vector

library:
  source-dirs: src
  exposed-modules:
    - Brainfuck

executables:
  app:
    main: Main.hs
    source-dirs: app
    dependencies:
      - brainfuck

tests:
  brainfuck-test:
    main: Driver.hs
    source-dirs:
      - test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - flow
      - hspec
      - hspec-discover
      - tasty
      - tasty-discover >= 4.1
      - tasty-hunit
      - tasty-hspec
      - tasty-smallcheck
      - tasty-rerun
      - brainfuck

  brainfuck-doctest:
    main: Doctest.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - doctest
      - Glob
      - QuickCheck
      - brainfuck

benchmarks:
  brainfuck-benchmark:
    main: Main.hs
    source-dirs: bench
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -O2
    dependencies:
      - criterion
      - brainfuck

stability: alpha (experimental)
