flags:
  text:
    integer-simple: false
packages:
- '.'
extra-deps:
- ListZipper-1.2.0.2
- QuickCheck-2.8.1
- StateVar-1.1.0.0
- attoparsec-0.13.0.0
- base-orphans-0.4.0
- bifunctors-5
- comonad-4.2.6
- contravariant-1.3.1.1
- distributive-0.4.4
- exceptions-0.8.0.2
- free-4.12.1
- hashable-1.2.3.3
- mtl-2.2.1
- nats-1
- prelude-extras-0.4
- primitive-0.6
- profunctors-5.1.1
- random-1.1
- scientific-0.3.3.8
- semigroupoids-5.0.0.2
- semigroups-0.16.2.2
- stm-2.4.4
- tagged-0.8.1
- text-1.2.1.1
- tf-random-0.5
- transformers-compat-0.4.0.4
- unordered-containers-0.2.5.1
- void-0.7
- doctest-0.10.0
- smallcheck-1.1.1
- tasty-0.10.1.2
- tasty-hunit-0.9.2
- tasty-smallcheck-0.8.0.1
- ansi-terminal-0.6.2.1
- async-2.0.2
- ghc-paths-0.1.0.9
- logict-0.6.0.2
- optparse-applicative-0.11.0.2
- regex-tdfa-rc-1.1.8.3
- syb-0.5.1
- unbounded-delays-0.1.0.9
- ansi-wl-pprint-0.6.7.2
- parsec-3.1.9
- regex-base-0.93.2
resolver: ghc-7.10
